services:
  mediadb-mysql:
    image: mysql:9.5.0
    container_name: mediadb-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mediadb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      mediadb:
        aliases:
          - mediadb-mysql
networks:
  mediadb:
    name: mediadb