spring.application.name=janick-mediaapi
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mediadb}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

# JPA configuration
spring.jpa.hibernate.use-new-id-generator-mappings=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false

# File upload limits
spring.servlet.multipart.max-file-size=400MB
spring.servlet.multipart.max-request-size=400MB

# JWT configuration
app.jwt.secret=efacd925768f87aedcadb8313d00f3c4b13472f2a1d3c29c54d2438fd99cc1d1
app.jwt.cookie-name=access-token
app.jwt.refresh-cookie-name=refresh-token
app.jwt.expiration-milliseconds=1800000
app.jwt.refresh-expiration-milliseconds=86400000
#app.jwt.expiration-milliseconds=60000
#app.jwt.refresh-expiration-milliseconds=300000

logging.level.root=INFO
spring.allowed.origin=${SPRING_ALLOWED_ORIGIN:http://localhost:5173}